# Generated by Django 5.1.4 on 2025-03-14 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='addhod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('Department', models.CharField(max_length=20)),
                ('joinig_date', models.DateField()),
                ('hodmobile', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='FEES',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Select_Department', models.CharField(max_length=20)),
                ('Department_Fees', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ROOL_NO', models.CharField(max_length=4)),
                ('s_name', models.CharField(max_length=20)),
                ('s_Department', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('F_name', models.CharField(max_length=20)),
                ('mobile', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('District', models.CharField(max_length=20)),
                ('Mandal', models.CharField(max_length=20)),
                ('Village', models.CharField(max_length=20)),
                ('select_Rool_number', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='application1.students')),
            ],
        ),
    ]
